alias ll="ls -al"
alias be="bundle exec"
alias rtest="SEED=1337 be ruby -Itest"
alias ptest="MYCASE__TESTING__PARALLELISM__ENABLED=1 SEED=1337 be ruby -Itest"
alias crtest="CHROME_DEBUG=1 SEED=1337 be ruby -Itest"
alias vim="nvim"
