version: 2
jobs:
  build:
    docker:
      - image: zenspider/emacs-ruby:2.4.1
    working_directory: ~/erm
    steps:
      - checkout
      - run: cd test && emacs --batch -Q -l enh-ruby-mode-test.el -f ert-run-tests-batch-and-exit
